spring:
  application:
    name: n1netails-liquibase
  datasource:
    url: jdbc:postgresql://localhost/n1netails
    username: postgres
    password: postgres
  driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

---
spring.config.activate.on-profile: docker
#########################################
# Postgres Config
#########################################
spring:
  datasource:
    url: jdbc:postgresql://db:5432/n1netails