spring.banner.location: classpath:banner.txt

spring:
  application:
    name: n1netails-liquibase
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:6789/n1netails}
    username: ${POSTGRES_USERNAME:n1netails}
    password: ${POSTGRES_PASSWORD:n1netails}
  driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: ntail
    enabled: true

#########################################
# Docker
#########################################
---
spring.config.activate.on-profile: docker
spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://db:5432/n1netails}