spring.profiles.active: local
server:
  port: ${PORT:9901}
  connection-timeout: -1
  max-http-header-size: -1
spring:
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    repositories:
      bootstrap-mode: default
