n1netails:
  email:
    enabled: ${EMAIL_ENABLED:false}

spring:
  mail:
    host: ${EMAIL_HOST:localhost}
    port: ${EMAIL_PORT:1025}
    username: ${EMAIL_USERNAME:host-username}
    password: ${EMAIL_PASSWORD:host-password}
    from: ${EMAIL_SENDER:support@n1netails.com}
    properties:
      mail:
        smtp:
          auth: ${EMAIL_PROPERTIES_AUTH:false}
          starttls.enable: ${EMAIL_PROPERTIES_STARTTLS_ENABLE:false}
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
