spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
#    initialization-mode: always
    url: jdbc:postgresql://localhost/n1netails
#    url: jdbc:postgresql://db:5433/n1netails
    username: postgres
    password: postgres
  jpa:
    defer-datasource-initialization: true
    show-sql: true
#    show-sql: false
    hibernate:
#      ddl-auto: create
#      ddl-auto: update
#      ddl-auto: none
      ddl-auto: validate
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: github-client-id
            clientSecret: github-client-secret
  sql:
    init:
      mode: never
#      mode: always


# TODO make different active profiles
---
spring.config.activate.on-profile: docker
#########################################
# Postgres Config
#########################################
spring:
  datasource:
    url: jdbc:postgresql://db:5432/n1netails
