spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
#    initialization-mode: always
    url: ${POSTGRES_URL:jdbc:postgresql://localhost/n1netails}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    defer-datasource-initialization: true
    show-sql: true
#    show-sql: false
    hibernate:
#      ddl-auto: create
#      ddl-auto: update
#      ddl-auto: none
      ddl-auto: validate
  sql:
    init:
      mode: never
#      mode: always

#########################################
# Docker
#########################################
---
spring.config.activate.on-profile: docker
spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://db:5432/n1netails}
